steps:
- name: gcr.io/cloud-builders/go
  args:
  - test
  - "./..."
  env:
  - PROJECT_ROOT=github.com/ninnemana/butler
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - "--cache-from"
  - us.gcr.io/ninneman-org/butler:latest
  - "-t"
  - us.gcr.io/ninneman-org/butler:$([[ $BRANCH_NAME = master ]] && echo latest || echo $SHORT_SHA)
  - "-f"
  - Dockerfile
  - "."
images:
- us.gcr.io/ninneman-org/butler:$([[ $BRANCH_NAME = master ]] && echo latest || echo $SHORT_SHA)
- us.gcr.io/ninneman-org/butler:$SHORT_SHA