steps:
- name: gcr.io/cloud-builders/go
  args:
  - test
  - "-coverprofile=profile.out"
  - "-covermode=atomic"
  - "./..."
  env:
  - PROJECT_ROOT=github.com/ninnemana/butler
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - "-t"
  - us.gcr.io/ninneman-org/butler:$SHORT_SHA
  - "-f"
  - Dockerfile
  - "."
- name: gcr.io/cloud-builders/curl
  args:
  - "-s"
  - "https://codecov.io/bash"
  - "|"
  - "bash"
  secretEnv: ['CODECOV_TOKEN']
images:
- us.gcr.io/ninneman-org/butler:$SHORT_SHA
secrets:
- kmsKeyName: projects/ninneman-org/locations/global/keyRings/continuous-integration/cryptoKeys/cloud-build
  secretEnv:
    CODECOV_TOKEN: CiQAotsHij6vFXqTqbpPmoeva4Um+B2NlTCXW1g9RTORjZx5A9gSTQBFyemJTFfujM/zpb5g/LEFsEygSsUAr+GwvAHBJNnHI2G9XK+RXPfBO3eXKYG0YZm4o3abbpb7+Yn2eUBl7QyRB7BMKPl9U+veHif1
